name: union_space
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"

flutter:
  uses-material-design: true
  assets:
    - assets/image 1.png
    - assets/image 6.png
    - assets/image 7.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  icon_size: 256
  adaptive_icon_background: "#ffffff" # atau "assets/icon/bg.png"
  image_path: "assets/cropped-Logo-US-Header-1 1.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/cropped-Logo-US-Header-1 1.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/cropped-Logo-US-Header-1 1.png"
    icon_size: 100 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/cropped-Logo-US-Header-1 1.png"
